helm:
  parameters:
  - name: image.repository
    value: eu.gcr.io/in2plane-cloud/nginx
    forcestring: true
  - name: image.tag
    value: develop@sha256:b670f11c712de88b4a7566b5a016b14bf8988d58027417c4a69217e1e9458401
    forcestring: true
