helm:
  parameters:
  - name: image.repository
    value: eu.gcr.io/in2plane-cloud/nginx
    forcestring: true
  - name: image.tag
    value: develop@sha256:3e8ce9cf137bd0d2da0e5e4ffd10950a622c450de666f0267deb5acd5a29000d
    forcestring: true
